x-env-vars: &x_env_vars .env

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    env_file: .env
    volumes:
      - sqlite_bp:/app/db

volumes:
  sqlite_bp:
