// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/check/transaction": {
            "post": {
                "description": "Check if a transaction meets the payment requirements",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Check a transaction",
                "parameters": [
                    {
                        "description": "Check transaction request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/constants.CheckTxRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/constants.CheckTxResponse"
                        }
                    }
                }
            }
        },
        "/find/transaction": {
            "post": {
                "description": "Find the latest transaction for a given address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Find the latest transaction",
                "parameters": [
                    {
                        "description": "Check transaction request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/constants.FindTxRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/constants.CheckTxResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "constants.CheckTxRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0xabc123..."
                },
                "currency": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/constants.CurrencyType"
                        }
                    ],
                    "example": "USDT"
                },
                "txid": {
                    "type": "string",
                    "example": "0xabc123..."
                }
            }
        },
        "constants.CheckTxResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/constants.PaymentStatus"
                }
            }
        },
        "constants.CurrencyType": {
            "type": "string",
            "enum": [
                "ETH",
                "USDT",
                "USDC"
            ],
            "x-enum-varnames": [
                "ETH",
                "USDT",
                "USDC"
            ]
        },
        "constants.FindTxRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "format": "hex",
                    "example": "0xabc123..."
                },
                "currency": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/constants.CurrencyType"
                        }
                    ],
                    "example": "USDT"
                }
            }
        },
        "constants.PaymentStatus": {
            "type": "string",
            "enum": [
                "pending",
                "received",
                "completed",
                "timeout",
                "failed",
                "mismatch"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusReceived",
                "StatusCompleted",
                "StatusTimeout",
                "StatusFailed",
                "StatusMismatch"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
